In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings

In [2]:
warnings.filterwarnings('ignore')

In [3]:
dataframe = pd.read_csv('heart-disease.csv')

In [4]:
dataframe.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [5]:
dataframe.shape

(303, 14)

In [6]:
round(dataframe.describe(),2)

age     sex      cp  trestbps    chol     fbs  restecg  thalach  \
count  303.00  303.00  303.00    303.00  303.00  303.00   303.00   303.00   
mean    54.37    0.68    0.97    131.62  246.26    0.15     0.53   149.65   
std      9.08    0.47    1.03     17.54   51.83    0.36     0.53    22.91   
min     29.00    0.00    0.00     94.00  126.00    0.00     0.00    71.00   
25%     47.50    0.00    0.00    120.00  211.00    0.00     0.00   133.50   
50%     55.00    1.00    1.00    130.00  240.00    0.00     1.00   153.00   
75%     61.00    1.00    2.00    140.00  274.50    0.00     1.00   166.00   
max     77.00    1.00    3.00    200.00  564.00    1.00     2.00   202.00   

        exang  oldpeak   slope      ca    thal  target  
count  303.00   303.00  303.00  303.00  303.00  303.00  
mean     0.33     1.04    1.40    0.73    2.31    0.54  
std      0.47     1.16    0.62    1.02    0.61    0.50  
min      0.00     0.00    0.00    0.00    0.00    0.00  
25%      0.00     0.00    1.00    0.00    2.00    0.00  
50%      0.00     0.80    1.00    0.00    2.00    1.00  
75%      1.00     1.60    2.00    1.00    3.00    1.00  
max      1.00     6.20    2.00    4.00    3.00    1.00

In [7]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [8]:
dataframe.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X = dataframe[['age','sex','cp','trestbps','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal']]
y = dataframe['target']

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=7738)

In [12]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((227, 13), (76, 13), (227,), (76,))

# Logistic Regression

In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:
model_log_reg = LogisticRegression()
model_log_reg.fit(X_train.values, y_train.values)

LogisticRegression()

In [15]:
model_log_reg.score(X_test, y_test)

0.9868421052631579

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

In [17]:
confusion_matrix(y_test,model_log_reg.predict(X_test))

array([[31,  0],
       [ 1, 44]], dtype=int64)

In [18]:
accuracy_score(y_test,model_log_reg.predict(X_test))

0.9868421052631579

In [19]:
precision_score(y_test,model_log_reg.predict(X_test))

1.0

In [20]:
recall_score(y_test,model_log_reg.predict(X_test))

0.9777777777777777

In [21]:
f1_score(y_test,model_log_reg.predict(X_test))

0.9887640449438202

# KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
model_knn = KNeighborsClassifier(n_neighbors=3)
model_knn.fit(X_train, y_train)

In [22]:
model_knn.score(X_test, y_test)

0.6447368421052632

In [23]:
confusion_matrix(y_test,model_knn.predict(X_test))

array([[20, 11],
       [16, 29]], dtype=int64)

In [24]:
accuracy_score(y_test,model_knn.predict(X_test))

0.6447368421052632

In [25]:
precision_score(y_test, model_knn.predict(X_test))

0.725

In [26]:
recall_score(y_test,model_knn.predict(X_test))

0.6444444444444445

In [27]:
f1_score(y_test,model_knn.predict(X_test))

0.6823529411764706

# SVM - Linear

In [28]:
from sklearn.svm import SVC

In [29]:
model_svc_lin = SVC(kernel='linear')
model_svc_lin.fit(X_train, y_train)

SVC(kernel='linear')

In [30]:
model_svc_lin.score(X_test, y_test)

0.9605263157894737

In [31]:
confusion_matrix(y_test,model_svc_lin.predict(X_test))

array([[30,  1],
       [ 2, 43]], dtype=int64)

In [32]:
accuracy_score(y_test,model_svc_lin.predict(X_test))

0.9605263157894737

In [33]:
precision_score(y_test, model_svc_lin.predict(X_test))

0.9772727272727273

In [34]:
recall_score(y_test,model_svc_lin.predict(X_test))

0.9555555555555556

In [35]:
f1_score(y_test,model_svc_lin.predict(X_test))

0.9662921348314608

# SVM - Poly

In [36]:
model_svc_poly = SVC(kernel='poly')
model_svc_poly.fit(X_train, y_train)

SVC(kernel='poly')

In [37]:
model_svc_poly.score(X_test, y_test)

0.7105263157894737

In [38]:
confusion_matrix(y_test,model_svc_poly.predict(X_test))

array([[19, 12],
       [10, 35]], dtype=int64)

In [39]:
accuracy_score(y_test,model_svc_poly.predict(X_test))

0.7105263157894737

In [40]:
precision_score(y_test, model_svc_poly.predict(X_test))

0.7446808510638298

In [41]:
recall_score(y_test,model_svc_poly.predict(X_test))

0.7777777777777778

In [42]:
f1_score(y_test,model_svc_poly.predict(X_test))

0.7608695652173912

# SVM - RBF

In [43]:
model_svc_rbf = SVC(kernel='rbf')
model_svc_rbf.fit(X_train, y_train)

SVC()

In [44]:
model_svc_rbf.score(X_test, y_test)

0.7105263157894737

In [45]:
confusion_matrix(y_test,model_svc_rbf.predict(X_test))

array([[17, 14],
       [ 8, 37]], dtype=int64)

In [46]:
accuracy_score(y_test,model_svc_rbf.predict(X_test))

0.7105263157894737

In [47]:
precision_score(y_test, model_svc_rbf.predict(X_test))

0.7254901960784313

In [48]:
recall_score(y_test,model_svc_rbf.predict(X_test))

0.8222222222222222

In [49]:
f1_score(y_test,model_svc_rbf.predict(X_test))

0.7708333333333334

# Decision Tree

In [50]:
from sklearn.tree import DecisionTreeClassifier

In [51]:
model_dt = DecisionTreeClassifier(max_depth=3, min_samples_leaf=1)
model_dt.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=3)

In [52]:
model_dt.score(X_test,y_test)

0.8947368421052632

# Below Data is tested just as curiosity

# Whole Data Test

# Logistic Regression

In [53]:
model_log_reg.score(X, y)

0.8646864686468647

In [54]:
confusion_matrix(y,model_log_reg.predict(X))

array([[109,  29],
       [ 12, 153]], dtype=int64)

In [55]:
accuracy_score(y,model_log_reg.predict(X))

0.8646864686468647

In [56]:
precision_score(y,model_log_reg.predict(X))

0.8406593406593407

In [57]:
recall_score(y,model_log_reg.predict(X))

0.9272727272727272

In [58]:
f1_score(y,model_log_reg.predict(X))

0.8818443804034581

# KNN

In [59]:
model_knn.score(X, y)

0.7722772277227723

In [60]:
confusion_matrix(y,model_knn.predict(X))

array([[103,  35],
       [ 34, 131]], dtype=int64)

In [61]:
accuracy_score(y,model_knn.predict(X))

0.7722772277227723

In [62]:
precision_score(y,model_knn.predict(X))

0.7891566265060241

In [63]:
recall_score(y,model_knn.predict(X))

0.793939393939394

In [64]:
f1_score(y,model_knn.predict(X))

0.7915407854984894

# SVM - Linear

In [65]:
model_svc_lin.score(X, y)

0.858085808580858

In [66]:
confusion_matrix(y,model_svc_lin.predict(X))

array([[107,  31],
       [ 12, 153]], dtype=int64)

In [67]:
accuracy_score(y,model_svc_lin.predict(X))

0.858085808580858

In [68]:
precision_score(y,model_svc_lin.predict(X))

0.8315217391304348

In [69]:
recall_score(y,model_svc_lin.predict(X))

0.9272727272727272

In [70]:
f1_score(y,model_svc_lin.predict(X))

0.8767908309455588

# SVM - Poly

In [71]:
model_svc_poly.score(X, y)

0.7029702970297029

In [72]:
confusion_matrix(y,model_svc_poly.predict(X))

array([[ 87,  51],
       [ 39, 126]], dtype=int64)

In [73]:
accuracy_score(y,model_svc_poly.predict(X))

0.7029702970297029

In [74]:
precision_score(y,model_svc_poly.predict(X))

0.711864406779661

In [75]:
recall_score(y,model_svc_poly.predict(X))

0.7636363636363637

In [76]:
f1_score(y,model_svc_poly.predict(X))

0.736842105263158

# SVM - RBF

In [77]:
model_svc_rbf.score(X, y)

0.6897689768976898

In [78]:
confusion_matrix(y,model_svc_rbf.predict(X))

array([[ 71,  67],
       [ 27, 138]], dtype=int64)

In [79]:
accuracy_score(y,model_svc_rbf.predict(X))

0.6897689768976898

In [80]:
precision_score(y,model_svc_rbf.predict(X))

0.6731707317073171

In [81]:
recall_score(y,model_svc_rbf.predict(X))

0.8363636363636363

In [82]:
f1_score(y,model_svc_rbf.predict(X))

0.7459459459459459

# Decision Tree

In [83]:
model_dt.score(X, y)

0.8382838283828383

In [84]:
confusion_matrix(y,model_dt.predict(X))

array([[116,  22],
       [ 27, 138]], dtype=int64)

In [85]:
accuracy_score(y,model_dt.predict(X))

0.8382838283828383

In [86]:
precision_score(y,model_dt.predict(X))

0.8625

In [87]:
recall_score(y,model_dt.predict(X))

0.8363636363636363

In [88]:
f1_score(y,model_dt.predict(X))

0.8492307692307692

# Trained Data Test

# Logistic Regression

In [89]:
model_log_reg.score(X_train, y_train)

0.8237885462555066

In [90]:
confusion_matrix(y_train,model_log_reg.predict(X_train))

array([[ 78,  29],
       [ 11, 109]], dtype=int64)

In [91]:
accuracy_score(y_train,model_log_reg.predict(X_train))

0.8237885462555066

In [92]:
precision_score(y_train,model_log_reg.predict(X_train))

0.7898550724637681

In [93]:
recall_score(y_train,model_log_reg.predict(X_train))

0.9083333333333333

In [94]:
f1_score(y_train,model_log_reg.predict(X_train))

0.8449612403100776

# KNN

In [95]:
model_knn.score(X_train, y_train)

0.8149779735682819

In [96]:
confusion_matrix(y_train,model_knn.predict(X_train))

array([[ 83,  24],
       [ 18, 102]], dtype=int64)

In [97]:
accuracy_score(y_train,model_knn.predict(X_train))

0.8149779735682819

In [98]:
precision_score(y_train,model_knn.predict(X_train))

0.8095238095238095

In [99]:
recall_score(y_train,model_knn.predict(X_train))

0.85

In [100]:
f1_score(y_train,model_knn.predict(X_train))

0.8292682926829269

# SVM - Linear

In [101]:
model_svc_lin.score(X_train, y_train)

0.8237885462555066

In [102]:
confusion_matrix(y_train,model_svc_lin.predict(X_train))

array([[ 77,  30],
       [ 10, 110]], dtype=int64)

In [103]:
accuracy_score(y_train,model_svc_lin.predict(X_train))

0.8237885462555066

In [104]:
precision_score(y_train,model_svc_lin.predict(X_train))

0.7857142857142857

In [105]:
recall_score(y_train,model_svc_lin.predict(X_train))

0.9166666666666666

In [106]:
f1_score(y_train,model_svc_lin.predict(X_train))

0.8461538461538461

# SVM - Poly

In [107]:
model_svc_poly.score(X_train, y_train)

0.7004405286343612

In [108]:
confusion_matrix(y_train,model_svc_poly.predict(X_train))

array([[68, 39],
       [29, 91]], dtype=int64)

In [109]:
accuracy_score(y_train,model_svc_poly.predict(X_train))

0.7004405286343612

In [110]:
precision_score(y_train,model_svc_poly.predict(X_train))

0.7

In [111]:
recall_score(y_train,model_svc_poly.predict(X_train))

0.7583333333333333

In [112]:
f1_score(y_train,model_svc_poly.predict(X_train))

0.728

# SVM - RBF

In [113]:
model_svc_rbf.score(X_train, y_train)

0.6828193832599119

In [114]:
confusion_matrix(y_train,model_svc_rbf.predict(X_train))

array([[ 54,  53],
       [ 19, 101]], dtype=int64)

In [115]:
accuracy_score(y_train,model_svc_rbf.predict(X_train))

0.6828193832599119

In [116]:
precision_score(y_train,model_svc_rbf.predict(X_train))

0.6558441558441559

In [117]:
recall_score(y_train,model_svc_rbf.predict(X_train))

0.8416666666666667

In [118]:
f1_score(y_train,model_svc_rbf.predict(X_train))

0.7372262773722628

# Decision Tree

In [119]:
model_dt.score(X_train, y_train)

0.8193832599118943

In [120]:
confusion_matrix(y_train,model_dt.predict(X_train))

array([[88, 19],
       [22, 98]], dtype=int64)

In [121]:
accuracy_score(y_train,model_dt.predict(X_train))

0.8193832599118943

In [122]:
precision_score(y_train,model_dt.predict(X_train))

0.8376068376068376

In [123]:
recall_score(y_train,model_dt.predict(X_train))

0.8166666666666667

In [124]:
f1_score(y_train,model_dt.predict(X_train))

0.8270042194092827